name: Block Main Push

on:
  push:
    branches:
      - main

jobs:
  block_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check Branch Name
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "Push to main branch is not allowed."
          exit 1
        fi
