name: Block Main Push

on:
  push:
    branches:
      - main

jobs:
  block_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check Branch Name
      run: |
        BRANCH_NAME=$(echo $GITHUB_REF | awk -F/ '{print $3}')
        if [ "$BRANCH_NAME" == "main" ]; then
          echo "Push to main branch is not allowed."
          exit 1
        fi